Nome Favorecido,Valor Parcela,UF,Nome Municipio,Fonte-Finalidade
CLAIR TERESINHA DIAS,70.00,RS,NOVO HAMBURGO,CAIXA - Programa Bolsa Familia
MARLENE SOUZA SILVA,70.00,BA,RUY BARBOSA,CAIXA - Programa Bolsa Familia
LILIANE DO SOCORRO MARQUES SOUSA,102.00,PA,BELEM,CAIXA - Programa Bolsa Familia
SALUSTIANO DAMACENO SANTOS,70.00,BA,PARIPIRANGA,CAIXA - Programa Bolsa Familia
LUCIENE PEREIRA DA SILVA,64.00,RJ,RIO DE JANEIRO,CAIXA - Programa Bolsa Familia
ELIZETE OLIVEIRA DOS SANTOS,166.00,BA,PORTO SEGURO,CAIXA - Programa Bolsa Familia
MARIA DE FATIMA GONCALVES PEREIRA,102.00,MG,CONTAGEM,CAIXA - Programa Bolsa Familia
MARIA GORETE ALVES MENDES,102.00,SP,OSASCO,CAIXA - Programa Bolsa Familia
VALDIRENE TEREZA MATOS,102.00,BA,ITAJUIPE,CAIXA - Programa Bolsa Familia
CARLA ALBERTA DE OLIVEIRA,230.00,SP,BAURU,CAIXA - Programa Bolsa Familia
CRISTIANE VIEIRA SILVA,134.00,RS,SANTANA DO LIVRAMENTO,CAIXA - Programa Bolsa Familia
TEREZINHA PEREIRA DA SILVA,166.00,MA,ACAILANDIA,CAIXA - Programa Bolsa Familia
SILVIA ALVES DA COSTA,140.00,SP,CAMPINAS,CAIXA - Programa Bolsa Familia
WLINE CLEMILDA DA SILVA,134.00,PE,FLORESTA,CAIXA - Programa Bolsa Familia
VERA DO ROSARIO MOREIRA ALCANTARA,102.00,MG,IBIRITE,CAIXA - Programa Bolsa Familia
EVALDO AP PEICHOTO,198.00,MG,SAO SEBASTIAO DO MARANHAO,CAIXA - Programa Bolsa Familia
ROSANGELA MARIA OLIVEIRA CARVALHO,142.00,MG,NOVA PONTE,CAIXA - Programa Bolsa Familia
SORAIA AQUINO DOS SANTOS,362.00,RJ,RIO DE JANEIRO,CAIXA - Programa Bolsa Familia
MAIARA MARIA DOS SANTOS PEREIRA,96.00,SP,GUARACI,CAIXA - Programa Bolsa Familia
DORIANE BELFORT RODRIGUES,102.00,MA,ITAPECURU MIRIM,CAIXA - Programa Bolsa Familia
WELDIA BARREIRA BORGES,134.00,GO,NOVO GAMA,CAIXA - Programa Bolsa Familia
ELIS REGINA SILVA MOURA,102.00,CE,TRAIRI,CAIXA - Programa Bolsa Familia
SIMONE FRANCISCA DE MORAIS,134.00,GO,TRINDADE,CAIXA - Programa Bolsa Familia
CELIA DE SOUZA MELO,142.00,SP,SAO BENTO DO SAPUCAI,CAIXA - Programa Bolsa Familia
JEANE LOURENCO DA COSTA,166.00,PA,TUCURUI,CAIXA - Programa Bolsa Familia
TIELLY FERREIRA WILL,166.00,ES,COLATINA,CAIXA - Programa Bolsa Familia
ROSELIA MASSANEIRO,102.00,SC,GASPAR,CAIXA - Programa Bolsa Familia
MARIA DO ROSARIO DA SILVA FERREIRA,282.00,MA,PIO XII,CAIXA - Programa Bolsa Familia
CILEIA LOPES SOARES,230.00,PA,MAE DO RIO,CAIXA - Programa Bolsa Familia
RENATA MARIA DE CARVALHO,134.00,PI,PICOS,CAIXA - Programa Bolsa Familia
JOSIANE JULIA SILVA DOS SANTOS,290.00,PB,CUITE DE MAMANGUAPE,CAIXA - Programa Bolsa Familia
MARIA SUELINE SANTANA DOS SANTOS,134.00,SE,ARACAJU,CAIXA - Programa Bolsa Familia
VERA ROSANE PEREIRA CRUZ,102.00,RS,SAPIRANGA,CAIXA - Programa Bolsa Familia
IRLES DE JESUS BORGES ALVES,172.00,MA,SAO LUIS,CAIXA - Programa Bolsa Familia
AGEMIRA JESUS DOS SANTOS,234.00,BA,PONTO NOVO,CAIXA - Programa Bolsa Familia
MARIA EVA RODRIGUES SCHEUER,70.00,RS,PORTO XAVIER,CAIXA - Programa Bolsa Familia
ROSANGELA JULIA CONCEIAO DA SILVA,102.00,PE,AGRESTINA,CAIXA - Programa Bolsa Familia
ELAINE CRISTINA SOARES LIMA,284.00,MG,SABARA,CAIXA - Programa Bolsa Familia
VIVIAN VIOLANTE DA SILVA,252.00,RJ,SAO FIDELIS,CAIXA - Programa Bolsa Familia
MARIA LUCIA PEREIRA DE SOUZA,134.00,SP,DIADEMA,CAIXA - Programa Bolsa Familia
CICERA MARIA PEREIRA DE SOUSA,210.00,CE,MAURITI,CAIXA - Programa Bolsa Familia
MARIA JOSE LIMA DE SOUZA,352.00,AM,CARAUARI,CAIXA - Programa Bolsa Familia
GRACIENE SEABRA CARDOSO,196.00,MG,BETIM,CAIXA - Programa Bolsa Familia
MONICA DE SOUZA JANUARIO,70.00,PB,SANTA RITA,CAIXA - Programa Bolsa Familia
MARIA JOSE DA SILVA,70.00,PE,RECIFE,CAIXA - Programa Bolsa Familia
BERENICE ARAUJO,212.00,MA,ALCANTARA,CAIXA - Programa Bolsa Familia
LEUZA MARIA DOS SANTOS,70.00,SP,SAO PAULO,CAIXA - Programa Bolsa Familia
PEMINA AMARO DA ROSA,422.00,RS,REDENTORA,CAIXA - Programa Bolsa Familia
LIDIANE CRISTINA APARECIDA CAMPOS,64.00,MG,CONSELHEIRO LAFAIETE,CAIXA - Programa Bolsa Familia
MARIA HELENA COELHO DIAS,102.00,RJ,SAO JOSE DE UBA,CAIXA - Programa Bolsa Familia
MARIA DO AMPARO SILVA VITALIANO,202.00,CE,MASSAPE,CAIXA - Programa Bolsa Familia
MARIA DE LOURDES DE LIMA EVANGELISTA,70.00,RJ,NOVA FRIBURGO,CAIXA - Programa Bolsa Familia
ZILDA CASSEMIRA DE SOUZA,70.00,MG,GURINHATA,CAIXA - Programa Bolsa Familia
INACIO PINHEIRO DAMASCENO,202.00,PA,MARACANA,CAIXA - Programa Bolsa Familia
IOLANDA MARIA GUSMAO TEODOZIO,70.00,AL,JACUIPE,CAIXA - Programa Bolsa Familia
MARIA GRINALDA MENDES NUNES,70.00,MA,CODO,CAIXA - Programa Bolsa Familia
ELIANA DOS SANTOS SILVA,176.00,SE,ARACAJU,CAIXA - Programa Bolsa Familia
CREUSA AURELIANO DA SILVA,150.00,MT,VARZEA GRANDE,CAIXA - Programa Bolsa Familia
AMELIA JESUINA LIMA,70.00,BA,BARRA DO MENDES,CAIXA - Programa Bolsa Familia
MARIA LETICIA SILVA NUNES,70.00,SP,GUARULHOS,CAIXA - Programa Bolsa Familia
ZENI DE LIMA TORRES,108.00,PR,CASCAVEL,CAIXA - Programa Bolsa Familia
ANAILDES ALVES DOS SANTOS,212.00,BA,RIO REAL,CAIXA - Programa Bolsa Familia
ISABEL SILVA VILAS BOAS,562.00,BA,IGRAPIUNA,CAIXA - Programa Bolsa Familia
RAIMUNDA LUCINEIDE DE LIMA GOMES,102.00,CE,SOBRAL,CAIXA - Programa Bolsa Familia
SELMA DE ABREU DOS SANTOS FRANCA,64.00,RJ,CAMPOS DOS GOITACAZES,CAIXA - Programa Bolsa Familia
ANA CARLA FACANHA SALES,122.00,CE,CAUCAIA,CAIXA - Programa Bolsa Familia
NILDELENE CAMPOS AMORAS,182.00,PA,TERRA ALTA,CAIXA - Programa Bolsa Familia
FRANCISCA SILVA FERREIRA,172.00,CE,FORTALEZA,CAIXA - Programa Bolsa Familia
MARIA DAS VIRGES BATISTA SILVA,70.00,CE,ARACATI,CAIXA - Programa Bolsa Familia
LIDIA APARECIDA DE SOUZA,134.00,MG,LAGOA DA PRATA,CAIXA - Programa Bolsa Familia
LIDIA FREITAS DE SOUZA,70.00,AM,MANAUS,CAIXA - Programa Bolsa Familia
ANA MARIA RIBEIRO DE MENEZES,212.00,PA,OBIDOS,CAIXA - Programa Bolsa Familia
MARIA DO CARMO DE PAULA,102.00,PR,CASCAVEL,CAIXA - Programa Bolsa Familia
ANTONIO DE AMORIM TELES,70.00,BA,ITABERABA,CAIXA - Programa Bolsa Familia
MARIA ROSA SOARES CARVALHO,218.00,MA,SAO MATEUS DO MARANHAO,CAIXA - Programa Bolsa Familia
MARIA JOSE MELO VIEIRA,92.00,CE,IPU,CAIXA - Programa Bolsa Familia
ANTONIA LIDIANE PAZ COSTA,102.00,CE,ACOPIARA,CAIXA - Programa Bolsa Familia
EMILIA RAASCH SCHMIDT,70.00,ES,VILA VALERIO,CAIXA - Programa Bolsa Familia
ROSEMEIRE AUGUSTA SILVA,166.00,SP,SAO PAULO,CAIXA - Programa Bolsa Familia
ELISANGELA RODRIGUES DOS REIS SANTOS,212.00,MA,SANTO ANTONIO DOS LOPES,CAIXA - Programa Bolsa Familia
ROSENILDA PEREIRA DA SILVA,154.00,SP,VOTORANTIM,CAIXA - Programa Bolsa Familia
ELIETES AMARAL,188.00,MA,PINHEIRO,CAIXA - Programa Bolsa Familia
MARIA IVONEIDE DA CONCEICAO ARAUJO,70.00,PE,BREJO DA MADRE DE DEUS,CAIXA - Programa Bolsa Familia
MARIA GLADIS VARGAS BARCELOS,70.00,RS,RIO PARDO,CAIXA - Programa Bolsa Familia
MARICELIA OLIVEIRA DIAS,70.00,MG,JACINTO,CAIXA - Programa Bolsa Familia
KELE DUTRA DUARTE,102.00,MG,SANTANA DO MANHUACU,CAIXA - Programa Bolsa Familia
MARIA LUCILENE DA COSTA,134.00,RN,ASSU,CAIXA - Programa Bolsa Familia
SANTA JANIRA SILVEIRA FRANCA,72.00,RS,LAJEADO,CAIXA - Programa Bolsa Familia
GRACIELE APARECIDA SANTANA MIRANDA,196.00,GO,TRINDADE,CAIXA - Programa Bolsa Familia
DOMINGAS FACUNDES DE SOUZA,352.00,TO,CHAPADA DA NATIVIDADE,CAIXA - Programa Bolsa Familia
TERESA AMORIM DOS SANTOS COSTA,174.00,MA,CAXIAS,CAIXA - Programa Bolsa Familia
NEUZA LOURENCO DA SILVA,112.00,SP,SAO PAULO,CAIXA - Programa Bolsa Familia
ANA PAULINA DE MORAIS,102.00,CE,CAUCAIA,CAIXA - Programa Bolsa Familia
MOACY BISPO DOS SANTOS,102.00,BA,POCOES,CAIXA - Programa Bolsa Familia
SIMONE LUCIA DOS SANTOS,212.00,RJ,NILOPOLIS,CAIXA - Programa Bolsa Familia
CASSIANE LIMA DE OLIVEIRA,252.00,RS,PALMARES DO SUL,CAIXA - Programa Bolsa Familia
EVANILDES SOUZA DOS SANTOS,182.00,BA,PRESIDENTE TANCREDO NEVES,CAIXA - Programa Bolsa Familia
CARMECITA MARQUES DA SILVA,188.00,PE,MIRANDIBA,CAIXA - Programa Bolsa Familia
ANA CLETE SANTOS PRUDENCIO,188.00,PI,SANTA LUZ,CAIXA - Programa Bolsa Familia
MARLEUDE FERNANDES DA SILVA,88.00,MT,BARRA DO GARCAS,CAIXA - Programa Bolsa Familia
MARIA SELMA FERREIRA DE SOUSA,70.00,BA,PLANALTO,CAIXA - Programa Bolsa Familia
FABIOLA DA SILVA MUTRAN BARROS,166.00,AM,MANAUS,CAIXA - Programa Bolsa Familia
MARIA ANTONIA DA SILVA COSTA,102.00,CE,CASCAVEL,CAIXA - Programa Bolsa Familia
JOAO PAULO SOARES DA SILVA,134.00,GO,CALDAS NOVAS,CAIXA - Programa Bolsa Familia
MARIA VALDENI ALVES DOS SANTOS,326.00,BA,OLINDINA,CAIXA - Programa Bolsa Familia
FRANCISCA ERIDAN DE SOUSA,140.00,CE,MOMBACA,CAIXA - Programa Bolsa Familia
ELISMAR DA SILVA BRITO,166.00,MA,COELHO NETO,CAIXA - Programa Bolsa Familia
ANDRESSA PAZ CARDOSO DE OLIVEIRA,134.00,RS,PAROBE,CAIXA - Programa Bolsa Familia
APARECIDA DE OLIVEIRA MOREIRA,102.00,PR,SANTO ANTONIO DA PLATINA,CAIXA - Programa Bolsa Familia
