Valor,Nome Orgao Superior,Nome Orgao,Nome Unidade Gestora,Nome Grupo Despesa,Nome Elemento Despesa,Nome Funcao,Nome Subfuncao,Nome Programa,Nome Acao,Nome Favorecido
58434.37,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Contratacao por Tempo Determinado,Direitos da Cidadania,Administracao Geral,Programa de Gestao e Manutencao da Secretaria de Politicas para as Mulheres,Administracao da Unidade,BANCO DO BRASIL SA [DIRECAO GERAL]
4530.74,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Contratacao por Tempo Determinado,Direitos da Cidadania,Administracao Geral,Programa de Gestao e Manutencao da Secretaria de Politicas para as Mulheres,Administracao da Unidade,BRB BANCO DE BRASILIA SA [BRB]
57889.31,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Contratacao por Tempo Determinado,Direitos da Cidadania,Administracao Geral,Programa de Gestao e Manutencao da Secretaria de Politicas para as Mulheres,Administracao da Unidade,CAIXA ECONOMICA FEDERAL [CEF MATRIZ]
13804.11,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Contratacao por Tempo Determinado,Direitos da Cidadania,Administracao Geral,Programa de Gestao e Manutencao da Secretaria de Politicas para as Mulheres,Administracao da Unidade,ITAU UNIBANCO S.A. [EST UNIF]
31606.09,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Contratacao por Tempo Determinado,Direitos da Cidadania,Administracao Geral,Programa de Gestao e Manutencao da Secretaria de Politicas para as Mulheres,Administracao da Unidade,BANCO SANTANDER (BRASIL) S.A.
2617.25,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Outros Beneficios Assistenciais do servidor e do militar,Administracao,Protecao e Beneficios ao Trabalhador,Programa de Gestao e Manutencao da Presidencia da Republica,Assistencia Pre-Escolar aos Dependentes dos Servidores Civis. Empregados e Militares,CAIXA ECONOMICA FEDERAL [CEF MATRIZ]
612.75,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Outros Beneficios Assistenciais do servidor e do militar,Administracao,Protecao e Beneficios ao Trabalhador,Programa de Gestao e Manutencao da Presidencia da Republica,Assistencia Pre-Escolar aos Dependentes dos Servidores Civis. Empregados e Militares,CAIXA ECONOMICA FEDERAL [CEF MATRIZ]
266.00,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Outros Beneficios Assistenciais do servidor e do militar,Administracao,Protecao e Beneficios ao Trabalhador,Programa de Gestao e Manutencao da Presidencia da Republica,Assistencia Pre-Escolar aos Dependentes dos Servidores Civis. Empregados e Militares,ITAU UNIBANCO S.A. [EST UNIF]
223.25,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Outros Beneficios Assistenciais do servidor e do militar,Direitos da Cidadania,Protecao e Beneficios ao Trabalhador,Programa de Gestao e Manutencao da Secretaria de Politicas para as Mulheres,Assistencia Pre-Escolar aos Dependentes dos Servidores Civis. Empregados e Militares,ITAU UNIBANCO S.A. [EST UNIF]
1318.27,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Material de Consumo,Administracao,Administracao Geral,Democracia e Aperfeicoamento da Gestao Publica,Funcionamento do Conselho Nacional de Seguranca Alimentar e Nutricional,ATHALAIA GRAFICA E EDITORA LTDA
697.50,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Material de Consumo,Administracao,Administracao Geral,Democracia e Aperfeicoamento da Gestao Publica,Funcionamento do Conselho Nacional de Seguranca Alimentar e Nutricional,ATHALAIA GRAFICA E EDITORA LTDA
794.25,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Material de Consumo,Administracao,Administracao Geral,Programa de Gestao e Manutencao da Presidencia da Republica,Administracao da Unidade,PISORAMA PISOS REVESTIMENTOS E DECORACOES LTDA - ME
49.72,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Material de Consumo,Administracao,Administracao Geral,Programa de Gestao e Manutencao da Presidencia da Republica,Administracao da Unidade,MULTIREDE DISTRIBUIDORA LTDA
138.59,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Material de Consumo,Administracao,Administracao Geral,Programa de Gestao e Manutencao da Presidencia da Republica,Administracao da Unidade,GASBALL ARMAZENADORA E DISTRIBUIDORA LTDA [GASBALL ARMAZENADORA E DISTRIBUIDORA]
11038.20,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Material de Consumo,Administracao,Administracao Geral,Programa de Gestao e Manutencao da Presidencia da Republica,Administracao da Unidade,GASBALL ARMAZENADORA E DISTRIBUIDORA LTDA [GASBALL ARMAZENADORA E DISTRIBUIDORA]
315.97,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Material de Consumo,Administracao,Administracao Geral,Programa de Gestao e Manutencao da Presidencia da Republica,Administracao da Unidade,DLF ENGENHARIA COMERCIO E REPRESENTACAO LTDA [ENGEMAFE]
733.93,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Material de Consumo,Administracao,Administracao Geral,Programa de Gestao e Manutencao da Presidencia da Republica,Administracao da Unidade,DLF ENGENHARIA COMERCIO E REPRESENTACAO LTDA [ENGEMAFE]
149.32,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Material de Consumo,Administracao,Administracao Geral,Programa de Gestao e Manutencao da Presidencia da Republica,Administracao da Unidade,DLF ENGENHARIA COMERCIO E REPRESENTACAO LTDA [ENGEMAFE]
276.37,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Material de Consumo,Administracao,Administracao Geral,Programa de Gestao e Manutencao da Presidencia da Republica,Administracao da Unidade,DLF ENGENHARIA COMERCIO E REPRESENTACAO LTDA [ENGEMAFE]
517.49,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Material de Consumo,Administracao,Administracao Geral,Programa de Gestao e Manutencao da Presidencia da Republica,Administracao da Unidade,DLF ENGENHARIA COMERCIO E REPRESENTACAO LTDA [ENGEMAFE]
517.89,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Material de Consumo,Administracao,Administracao Geral,Programa de Gestao e Manutencao da Presidencia da Republica,Administracao da Unidade,DLF ENGENHARIA COMERCIO E REPRESENTACAO LTDA [ENGEMAFE]
344.13,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Material de Consumo,Administracao,Administracao Geral,Programa de Gestao e Manutencao da Presidencia da Republica,Administracao da Unidade,DLF ENGENHARIA COMERCIO E REPRESENTACAO LTDA [ENGEMAFE]
8334.90,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Material de Consumo,Administracao,Administracao Geral,Programa de Gestao e Manutencao da Presidencia da Republica,Administracao da Unidade,DLF ENGENHARIA COMERCIO E REPRESENTACAO LTDA [ENGEMAFE]
5538.51,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Material de Consumo,Administracao,Administracao Geral,Programa de Gestao e Manutencao da Presidencia da Republica,Administracao da Unidade,DLF ENGENHARIA COMERCIO E REPRESENTACAO LTDA [ENGEMAFE]
22.25,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Material de Consumo,Administracao,Administracao Geral,Programa de Gestao e Manutencao da Presidencia da Republica,Administracao da Unidade,SEGGRAF IMPRESSOS DE SEGURANCA LTDA - EPP
44.50,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Material de Consumo,Administracao,Administracao Geral,Programa de Gestao e Manutencao da Presidencia da Republica,Administracao da Unidade,SEGGRAF IMPRESSOS DE SEGURANCA LTDA - EPP
2225.04,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Material de Consumo,Administracao,Administracao Geral,Programa de Gestao e Manutencao da Presidencia da Republica,Administracao da Unidade,GASBRAX DO BRASIL DISTRIBUIDORA DE GASES LTDA - ME [GASBRAX DO BRASIL]
33065.19,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Material de Consumo,Administracao,Administracao Geral,Programa de Gestao e Manutencao da Presidencia da Republica,Administracao da Unidade,WR COMERCIAL DE ALIMENTOS E SERVICOS LTDA - ME [WR COMERCIAL DE ALIMENTOS E SERVICOS]
15921.57,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Material de Consumo,Administracao,Administracao Geral,Programa de Gestao e Manutencao da Presidencia da Republica,Administracao da Unidade,WR COMERCIAL DE ALIMENTOS E SERVICOS LTDA - ME [WR COMERCIAL DE ALIMENTOS E SERVICOS]
49046.02,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Material de Consumo,Administracao,Administracao Geral,Programa de Gestao e Manutencao da Presidencia da Republica,Administracao da Unidade,WR COMERCIAL DE ALIMENTOS E SERVICOS LTDA - ME [WR COMERCIAL DE ALIMENTOS E SERVICOS]
23424.52,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Material de Consumo,Administracao,Administracao Geral,Programa de Gestao e Manutencao da Presidencia da Republica,Administracao da Unidade,WR COMERCIAL DE ALIMENTOS E SERVICOS LTDA - ME [WR COMERCIAL DE ALIMENTOS E SERVICOS]
198.90,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Material de Consumo,Administracao,Administracao Geral,Programa de Gestao e Manutencao da Presidencia da Republica,Administracao da Unidade,CAP - PAISAGISMO. URBANISMO E COMERCIO LTDA - ME [IPE. PAISAGISMO. URBANISMO E CONSTRUCOES]
3201.10,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Material de Consumo,Administracao,Administracao Geral,Programa de Gestao e Manutencao da Presidencia da Republica,Administracao da Unidade,CAP - PAISAGISMO. URBANISMO E COMERCIO LTDA - ME [IPE. PAISAGISMO. URBANISMO E CONSTRUCOES]
600.00,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Material de Consumo,Administracao,Administracao Geral,Programa de Gestao e Manutencao da Presidencia da Republica,Administracao da Unidade,EDUARDO SIQUEIRA BARBOSA - ME [MARI PAPELARIA]
77760.00,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Material de Consumo,Administracao,Administracao Geral,Programa de Gestao e Manutencao da Presidencia da Republica,Administracao da Unidade,E K MORE PAPEIS - ME [E K M PAPEIS]
6840.00,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Material de Consumo,Administracao,Administracao Geral,Programa de Gestao e Manutencao da Presidencia da Republica,Administracao da Unidade,AUTOLIMPE INDUSTRIA E COMERCIO DE PRODUTOS AUTOMOTIVOS LTDA - ME [AUTOLIMPE]
2449.93,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Material de Consumo,Administracao,Administracao Geral,Programa de Gestao e Manutencao da Presidencia da Republica,Administracao da Unidade,R & J COMERCIO DE EQUIPAMENTOS CONTRA INCENDIO. EPI E PRODUTOS HOSPITALARES LTDA - ME [EXTINMEDH]
493.00,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Material de Consumo,Administracao,Administracao Geral,Programa de Gestao e Manutencao da Presidencia da Republica,Administracao da Unidade,ART STILO PAPELARIA. LIVRARIA. COMERCIO E INFORMATICA LTDA - EPP
135000.00,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Material de Consumo,Administracao,Administracao Geral,Programa de Gestao e Manutencao da Presidencia da Republica,Administracao da Unidade,TOPVISION COMERCIO E SERVICOS LTDA - EPP [TOPVISION COMERCIO E SERVICO]
336.96,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Material de Consumo,Administracao,Administracao Geral,Programa de Gestao e Manutencao da Presidencia da Republica,Administracao da Unidade,D&F COMERCIO DE PAPEIS LTDA. - ME [D&F PAPEIS.]
760.25,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Material de Consumo,Administracao,Administracao Geral,Programa de Gestao e Manutencao da Presidencia da Republica,Administracao da Unidade,PALMAS EDITORA GRAFICA LTDA - ME [GRAFICA PALMAS]
0.93,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Material de Consumo,Administracao,Administracao Geral,Programa de Gestao e Manutencao da Presidencia da Republica,Administracao da Unidade,LINDE GASES LTDA [AGA]
11.05,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Material de Consumo,Administracao,Administracao Geral,Programa de Gestao e Manutencao da Presidencia da Republica,Administracao da Unidade,HBL CARIMBOS E PLACAS INDUSTRIA E COMERCIO LTDA - ME [HBL CARIMBOS E PLACAS]
248.47,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Material de Consumo,Administracao,Administracao Geral,Programa de Gestao e Manutencao da Presidencia da Republica,Administracao da Unidade,HBL CARIMBOS E PLACAS INDUSTRIA E COMERCIO LTDA - ME [HBL CARIMBOS E PLACAS]
87.72,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Passagens e Despesas com Locomocao,Administracao,Planejamento e Orcamento,Democracia e Aperfeicoamento da Gestao Publica,Formulacao. Desenvolvimento e Capacitacao para Participacao Social,EMPRESA BRASILEIRA DE INFRA-ESTRUTURA AEROPORTUARIA [INFRAERO]
3.11,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Passagens e Despesas com Locomocao,Administracao,Planejamento e Orcamento,Democracia e Aperfeicoamento da Gestao Publica,Formulacao. Desenvolvimento e Capacitacao para Participacao Social,EMPRESA BRASILEIRA DE INFRA-ESTRUTURA AEROPORTUARIA [INFRAERO]
9.33,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Passagens e Despesas com Locomocao,Administracao,Planejamento e Orcamento,Democracia e Aperfeicoamento da Gestao Publica,Formulacao. Desenvolvimento e Capacitacao para Participacao Social,EMPRESA BRASILEIRA DE INFRA-ESTRUTURA AEROPORTUARIA [INFRAERO]
34.08,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Passagens e Despesas com Locomocao,Administracao,Planejamento e Orcamento,Democracia e Aperfeicoamento da Gestao Publica,Formulacao. Desenvolvimento e Capacitacao para Participacao Social,EMPRESA BRASILEIRA DE INFRA-ESTRUTURA AEROPORTUARIA [INFRAERO]
5.90,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Passagens e Despesas com Locomocao,Administracao,Planejamento e Orcamento,Democracia e Aperfeicoamento da Gestao Publica,Formulacao. Desenvolvimento e Capacitacao para Participacao Social,EMPRESA BRASILEIRA DE INFRA-ESTRUTURA AEROPORTUARIA [INFRAERO]
6.15,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Passagens e Despesas com Locomocao,Administracao,Planejamento e Orcamento,Democracia e Aperfeicoamento da Gestao Publica,Formulacao. Desenvolvimento e Capacitacao para Participacao Social,EMPRESA BRASILEIRA DE INFRA-ESTRUTURA AEROPORTUARIA [INFRAERO]
6.15,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Passagens e Despesas com Locomocao,Administracao,Planejamento e Orcamento,Democracia e Aperfeicoamento da Gestao Publica,Formulacao. Desenvolvimento e Capacitacao para Participacao Social,EMPRESA BRASILEIRA DE INFRA-ESTRUTURA AEROPORTUARIA [INFRAERO]
60.24,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Passagens e Despesas com Locomocao,Administracao,Planejamento e Orcamento,Democracia e Aperfeicoamento da Gestao Publica,Formulacao. Desenvolvimento e Capacitacao para Participacao Social,EMPRESA BRASILEIRA DE INFRA-ESTRUTURA AEROPORTUARIA [INFRAERO]
3.11,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Passagens e Despesas com Locomocao,Administracao,Planejamento e Orcamento,Democracia e Aperfeicoamento da Gestao Publica,Formulacao. Desenvolvimento e Capacitacao para Participacao Social,EMPRESA BRASILEIRA DE INFRA-ESTRUTURA AEROPORTUARIA [INFRAERO]
21.75,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Passagens e Despesas com Locomocao,Administracao,Planejamento e Orcamento,Democracia e Aperfeicoamento da Gestao Publica,Formulacao. Desenvolvimento e Capacitacao para Participacao Social,EMPRESA BRASILEIRA DE INFRA-ESTRUTURA AEROPORTUARIA [INFRAERO]
25.15,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Passagens e Despesas com Locomocao,Administracao,Planejamento e Orcamento,Democracia e Aperfeicoamento da Gestao Publica,Formulacao. Desenvolvimento e Capacitacao para Participacao Social,EMPRESA BRASILEIRA DE INFRA-ESTRUTURA AEROPORTUARIA [INFRAERO]
7.74,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Passagens e Despesas com Locomocao,Administracao,Planejamento e Orcamento,Democracia e Aperfeicoamento da Gestao Publica,Formulacao. Desenvolvimento e Capacitacao para Participacao Social,EMPRESA BRASILEIRA DE INFRA-ESTRUTURA AEROPORTUARIA [INFRAERO]
4.30,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Passagens e Despesas com Locomocao,Administracao,Planejamento e Orcamento,Democracia e Aperfeicoamento da Gestao Publica,Formulacao. Desenvolvimento e Capacitacao para Participacao Social,EMPRESA BRASILEIRA DE INFRA-ESTRUTURA AEROPORTUARIA [INFRAERO]
12.51,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Passagens e Despesas com Locomocao,Administracao,Planejamento e Orcamento,Democracia e Aperfeicoamento da Gestao Publica,Formulacao. Desenvolvimento e Capacitacao para Participacao Social,EMPRESA BRASILEIRA DE INFRA-ESTRUTURA AEROPORTUARIA [INFRAERO]
12.44,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Passagens e Despesas com Locomocao,Administracao,Planejamento e Orcamento,Democracia e Aperfeicoamento da Gestao Publica,Formulacao. Desenvolvimento e Capacitacao para Participacao Social,EMPRESA BRASILEIRA DE INFRA-ESTRUTURA AEROPORTUARIA [INFRAERO]
28.59,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Passagens e Despesas com Locomocao,Administracao,Planejamento e Orcamento,Democracia e Aperfeicoamento da Gestao Publica,Formulacao. Desenvolvimento e Capacitacao para Participacao Social,EMPRESA BRASILEIRA DE INFRA-ESTRUTURA AEROPORTUARIA [INFRAERO]
12.44,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Passagens e Despesas com Locomocao,Administracao,Planejamento e Orcamento,Democracia e Aperfeicoamento da Gestao Publica,Formulacao. Desenvolvimento e Capacitacao para Participacao Social,EMPRESA BRASILEIRA DE INFRA-ESTRUTURA AEROPORTUARIA [INFRAERO]
42.88,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Passagens e Despesas com Locomocao,Administracao,Planejamento e Orcamento,Democracia e Aperfeicoamento da Gestao Publica,Formulacao. Desenvolvimento e Capacitacao para Participacao Social,EMPRESA BRASILEIRA DE INFRA-ESTRUTURA AEROPORTUARIA [INFRAERO]
19.51,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Passagens e Despesas com Locomocao,Administracao,Planejamento e Orcamento,Democracia e Aperfeicoamento da Gestao Publica,Formulacao. Desenvolvimento e Capacitacao para Participacao Social,EMPRESA BRASILEIRA DE INFRA-ESTRUTURA AEROPORTUARIA [INFRAERO]
10.93,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Passagens e Despesas com Locomocao,Administracao,Planejamento e Orcamento,Democracia e Aperfeicoamento da Gestao Publica,Formulacao. Desenvolvimento e Capacitacao para Participacao Social,EMPRESA BRASILEIRA DE INFRA-ESTRUTURA AEROPORTUARIA [INFRAERO]
6.21,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Passagens e Despesas com Locomocao,Administracao,Planejamento e Orcamento,Democracia e Aperfeicoamento da Gestao Publica,Formulacao. Desenvolvimento e Capacitacao para Participacao Social,EMPRESA BRASILEIRA DE INFRA-ESTRUTURA AEROPORTUARIA [INFRAERO]
30.38,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Passagens e Despesas com Locomocao,Administracao,Planejamento e Orcamento,Democracia e Aperfeicoamento da Gestao Publica,Formulacao. Desenvolvimento e Capacitacao para Participacao Social,EMPRESA BRASILEIRA DE INFRA-ESTRUTURA AEROPORTUARIA [INFRAERO]
1370.52,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Passagens e Despesas com Locomocao,Administracao,Planejamento e Orcamento,Democracia e Aperfeicoamento da Gestao Publica,Formulacao. Desenvolvimento e Capacitacao para Participacao Social,TAM LINHAS AEREAS S/A.
161.02,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Passagens e Despesas com Locomocao,Administracao,Planejamento e Orcamento,Democracia e Aperfeicoamento da Gestao Publica,Formulacao. Desenvolvimento e Capacitacao para Participacao Social,TAM LINHAS AEREAS S/A.
305.69,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Passagens e Despesas com Locomocao,Administracao,Planejamento e Orcamento,Democracia e Aperfeicoamento da Gestao Publica,Formulacao. Desenvolvimento e Capacitacao para Participacao Social,TAM LINHAS AEREAS S/A.
146.92,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Passagens e Despesas com Locomocao,Administracao,Planejamento e Orcamento,Democracia e Aperfeicoamento da Gestao Publica,Formulacao. Desenvolvimento e Capacitacao para Participacao Social,TAM LINHAS AEREAS S/A.
518.31,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Passagens e Despesas com Locomocao,Administracao,Planejamento e Orcamento,Democracia e Aperfeicoamento da Gestao Publica,Formulacao. Desenvolvimento e Capacitacao para Participacao Social,TAM LINHAS AEREAS S/A.
443.09,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Passagens e Despesas com Locomocao,Administracao,Planejamento e Orcamento,Democracia e Aperfeicoamento da Gestao Publica,Formulacao. Desenvolvimento e Capacitacao para Participacao Social,TAM LINHAS AEREAS S/A.
354.40,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Passagens e Despesas com Locomocao,Administracao,Planejamento e Orcamento,Democracia e Aperfeicoamento da Gestao Publica,Formulacao. Desenvolvimento e Capacitacao para Participacao Social,TAM LINHAS AEREAS S/A.
183.37,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Passagens e Despesas com Locomocao,Administracao,Planejamento e Orcamento,Democracia e Aperfeicoamento da Gestao Publica,Formulacao. Desenvolvimento e Capacitacao para Participacao Social,TAM LINHAS AEREAS S/A.
70.15,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Passagens e Despesas com Locomocao,Administracao,Planejamento e Orcamento,Democracia e Aperfeicoamento da Gestao Publica,Formulacao. Desenvolvimento e Capacitacao para Participacao Social,TAM LINHAS AEREAS S/A.
267.05,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Passagens e Despesas com Locomocao,Administracao,Planejamento e Orcamento,Democracia e Aperfeicoamento da Gestao Publica,Formulacao. Desenvolvimento e Capacitacao para Participacao Social,TAM LINHAS AEREAS S/A.
198.18,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Passagens e Despesas com Locomocao,Administracao,Planejamento e Orcamento,Democracia e Aperfeicoamento da Gestao Publica,Formulacao. Desenvolvimento e Capacitacao para Participacao Social,TAM LINHAS AEREAS S/A.
307.73,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Passagens e Despesas com Locomocao,Administracao,Planejamento e Orcamento,Democracia e Aperfeicoamento da Gestao Publica,Formulacao. Desenvolvimento e Capacitacao para Participacao Social,TAM LINHAS AEREAS S/A.
20.24,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,SECRETARIA DE ADMINISTRACAO/PR,Outras Despesas Correntes,Passagens e Despesas com Locomocao,Administracao,Planejamento e Orcamento,Democracia e Aperfeicoamento da Gestao Publica,Formulacao. Desenvolvimento e Capacitacao para Participacao Social,TAM LINHAS AEREAS S/A.
