...xBxxxBxxxxxxxxxxx
...xxBxxxxxxxxxxxxxx
...xxxxxxBxxxxxxxxxx
...xxxxxxxxxxxxxBxxx
...xxxxxxxxxxBBxxxxx
1..xxxBxxxxxxxxxxxxx
.....xxx.xxxxxxxBxxx
........xxxxxxxxxxxx
........xBxxxxxxxxxx
...4....xxxxxxxxBxxx
...1.....3...xxxxxxx
.............xxxxxxx
.............xBxxxxx
....2........xxx1...
.1..................
....................
.2........7.2....2..
...3................
...........4........
....................
