......xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx............
......xxxxxxxxxxxxxxxxxxxxxxxBxxxxxxxx..xxxxxxxxxx
......xxxxxxxxxxxxxxxxxxxxxxBxxxxxxxxxxxxxxxxxxxxx
.....xxxxxxxxxBBxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
.....xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
.....xxxxxxxxxxxxBxxxBxxxxxxxxxxxxxxxxxxxxxxxxxxxx
.....xxxxxxxxxxxxxxxxxxxxxxxxxxxBBxxxxxxxxxxxBxxxx
.....xxxxxxxxxxxxxxBxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
.....xxxxxxxBxxxxxxxxxxxxxxxxxxxxxxxxxxBxxxxxxxxxx
9....xxxxxxxxxxxxxxxBxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
.....xxxxxxxBxxxxxxxxxxxxxxxxxxBBBBxxxxxxxxxxxxxxx
....xxxxxxxxxxxxxxxxxxxxxBxxxxxxxxxxxxxxxxxxxxxxxx
....xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxBxxxxBxxxxBxx
....xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
....xxxxxxxxxxxxxxxxBxxxxxxxxxx..xxxxxxxxxxxxxxxxx
....xxxxBxxxxxxxxxxxxxxxxxxxxxx..xxxxxxxxxxxxxxxxx
....xxxxxxxxxxxxxxxxxxxBxxxxxxx..xxxxxxxBxxBxxxxxx
....xxxxxxxxxxxxxxxxxxxxxxxxxxx....xxxxxxxxxxxxxxx
....xxxxxxxxxxxxxxxxxxxBxxxxxxx....xxxxxxxxxxxxxxx
....xxxxxxxxxxxxxxxxxBxxxxxxxxx....xxxxxxxxBxxxxxx
.............xxxxxxxxxxxxxxBxxx....xxxxxxxxxxxxxxx
.............xxxxxxxxxxxxxxxxxx....xxxxxxBxxxxxxxx
..............xxxxxxxxxxxxxxxxx......xxxxxxxxxxxxx
..............xxxxxxxxxxxxxxxxx.....xxxxxxxxxxxxxx
..............xxxxxxxxxxxxxxxxx.....xxxxxxBxBxBxxx
..............xxxxxxBxxxxxxxxxxxxxxxxxBxBxxxxxxxxx
..............xxxxxxxxxxxxxBxxxxxxxxxxBxxxxxxxxxxx
..............xxxxxxxxxxxxxxxxxxxxxxxxBxxxxxxxxxxx
......9.......xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
..............xxxxxxxxxxxxxxxxxBxBxxxxxxxxxxxxxxxx
.......9......xxxxxxxxxxxxxxxxxxxxxxxBxxxBxxxx....
..............xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx...
.2....2....................xxxxxxxxxxxxxxxxxxxx...
........8..................xxxxxxxxxxxxxxxxxxxx...
.................................xxxxxxxxxxxxxx...
...............33..................xxxxxBxxxxxx...
..................2................xxxxxxBxxxxx...
...................................xxxxxBxxxxxxxxx
.......2............9..............xxxxxxBxxxxxxxx
.......xxxxxxxxxxx.................xxBxxxBxxxxxxxx
.......xBxxxxxxxxx.................xxxxxxxBxxxxxxx
....3..xxBxBxxxxxx............1.....xBxxxxxBxxxxxx
.......xxxxxxxBxxxxxx...............xxxxxxxxxxxxxx
.......xxxxxxxxxxxxxxx..............xxxxxxxxxxxxxx
.....1.....xxxxxxxxxxxxx....xxxxx.7.xxxxxxxxxxxxxx
...........xxxxxxBxBxxxxxxxxxxxxx..xxxxxxxxxxxxBBx
..............xxxxxxxBxxxxxxxxBxxxxxxxxBxxxBxxxxxx
..9...2.......xxxxxxxxxBxBxBBxxxxxxxxBxxxxxxxxxxxx
..............xxxxxxxxxxxxxxxxxxBBxxxxxxxxxxxxxxxx
.....................xxxxBxxxxxxxxxBxxxxxxxxxxxxxB
