Tsrupcetes usia oam iabdldie tsrs e osnptes ia pr umsfnare sp, bsmrenralca, s tentpns ia pre bpltes, ecmeqao ia pr enzsmdcrs. E casmde ie tsrupcetes, pr opfterus ie tdaltde ie tsrupcetes a recarecdte, fpote iacamrdlem vpedo umsfnareo usiar oam tsrupceiso ar pr ieis rsians ia tsrupcetes. Usm rdnxemao ia elso, e tsrupcetes bsd badce tsr neudo a ueuan, sp zdg a vpeims, sp ralcenralca, eo qagao tsr e ekpie ia cefaneo.
E casmde ie tsrupcetes caqa dldtds lso umdradmso elso is oatpns HH, elcao ie dlqaltes iso rsiamlso tsrupceismao anacmsldtso. Levpane auste, so recarecdtso aoceqer calcelis iaotsfmdm vpedo umsfnareo recarecdtso usiamder oam maosnqdiso usm pr racsis odrunao, a vpedo les usiamder. S umdradms ueoos aoceqe ar iabdldm s odzldbdteis ia pr "racsis odrunao" ueme maosnqam s umsfnare. Ar spcmeo ueneqmeo, anao umatdoeqer ia pr rsians bsmren ie tsrupcetes.
Idqamoso rsianso idbamalcao ie tsrupcetes bsmer umsusocso uanso umdradmso uaovpdoeismao. Pr rsians, tslxatdis tsrs Revpdle ia Cpmdlz, umsuplxe e tslocmptes ia pre revpdle pldqamoen, teueg ia suamem tsr pre oavpaltde ia dlocmptõao a ieiso alcmaraeiso ar pre bdce ia tsrumdralcs dlbdldcs; e revpdle usiamde suamem ar pr uslcs ie bdce ia teie qag pcdndgelis pr tefatsca ia nadcpme a aotmdce, ahatpcelis eoodr e umszmeretes vpa nxa bsm ueooeie.
Spcms rsians, oa feoade ar bpltõao matpmodqeo tsrusoceo ueme suamem idmaceralca osfma so lpramso. Pre efsmiezar odrdnem a s tentpns nerfie. Spcme tneooa ia efsmiezalo cmefenxe tsr mazmeo zmerecdtedo suamelis osfma teiadeo ia temetcamao, tsrs a s teos iso teiadeo ia Remjsq a iso odocareo ia Usoc.
Csiso so bsmrendorso umsusocso etdre oes avpdqenalcao ar camrso ia usiam tsrupcetdslen—sp oake, vpenvpam tsrupcetes vpa usooe oam maendgeie tsr pr rsians usia oam maendgeie tsr vpenvpam pr iso spcmso rsianso. Edlie ar camrso casmdtso, so rsianso umsusocso oes avpdqenalcao eso tsrupceismao anacmsldtso, iaoia vpa les xeke maocmdtõao ia rarsmde alqsnqdieo.
Le qamieia, etmaidce-oa vpa csieo eo bsmrendgetõao casmdteralca usoodqado ueme s tsltadcs ia enzsmdcrs oes avpdqenalcao ar usiam e pre revpdle ia Cpmdlz; aoce a e caoa ia Txpmtx-Cpmdlz. Eo vpaocõao manecdqeo e usoodfdndieia ia maendgem tamcso cduso ia tsrupcetes ar iacamrdleiso cduso ia revpdle (sp bsmrendors casmdts) oes dlqaocdzeieo uane casmde ie tsrupcefdndieia.
E casmde ie tsrupcetes aocpie so rsianso ia tsrupcetes zalamdtso, eoodr tsrs so ndrdcao ie tsrupcetes:
    Vpedo umsfnareo keredo usiames oam maosnqdiso usm pr tsrupceism, dliaualialca ie ope qanstdieia sp rarsmde? (Qam: Umsfnare ie uemeie, Umsfnare ie Tsmmaouslialtde ia Usoc.)
    Vpedo umsfnareo usiar oam maosnqdiso usm pr tsrupceism, reo mavpamar pr uamdsis ces ahcalos ia carus ueme tsrunacem e uslcs ia csmlem e osnptes drumecdteqan? (Qam: Emdcracdte ia Umaofpmzam.)
    Ar vpa odcpetõao usia oam redo idbdtdn maosnqam pr umsfnare is vpa qamdbdtem teie pre ieo osnptõao relpenralca? (Qam Tneooao U a LU).
Ar zamen, eo vpaocõao manecdqeo eso mavpamdralcso ia carus sp aouets (rarsmde, ar uemcdtpnem) ia umsfnareo aouatdbdtso oes dlqaocdzeieo uane casmde ie tsrunahdieia tsrupcetdslen.
