Muito mais do que gostar de jogos eletronicos, de navegar na internet e de tudo que se relaciona com computadores, para ser bem sucedido no curso de Engenharia de Computacao, o estudante precisa de raciocinio logico, conhecimentos de fisica e de matematica, dedicacao em tempo integral e muita disposicao para aprender.
Sem se deixar levar pelos modismos tecnologicos, constantemente em mudanca na area de computacao, o curso propicia uma formacao solida e abrangente ao futuro engenheiro, tornando-o capaz de adaptar-se aos novos desenvolvimentos e tecnologias que surgirem em sua carreira profissional.
Embasamento e flexibilidade
Oferecido em parceria por duas unidades da Unicamp – a Faculdade de Engenharia Eletrica e de Computacao (FEEC) e o Instituto de Computacao (IC) – o curso de Engenharia de Computacao e ministrado em periodo integral e pode ser concluido em dez semestres.
Alem de entrar em contato com disciplinas que apresentam os fundamentos da computacao logo nos primeiros semestres, como programacao, estruturas de dados e analise de algoritmos, o aluno devera frequentar disciplinas basicas de engenharia durante os dois primeiros anos da graduacao. Constam do curriculo, por exemplo, quatro semestres de fisica e tres semestres de calculo.
A partir do terceiro ano, projetos de sistemas integrados de hardware e software passam a fazer parte da grade curricular, alem do embasamento teorico proporcionado por disciplinas como circuitos eletricos e engenharia de software.
Disciplinas de formacao geral como ciencias do ambiente, topicos em humanidades, direito e economia integram o conjunto das disciplinas obrigatorias. Sendo a flexibilidade uma caracteristica marcante do curso, as disciplinas obrigatorias podem ser complementadas com disciplinas eletivas que tratam de topicos avancados em computacao, como multimidia, internet ou processamento de imagens aplicado a medicina.
Para consolidar sua formacao academica, o estudante pode participar de pesquisas supervisionadas por professores. Alunos que desenvolvem projetos de pesquisa tem a possibilidade de obter uma bolsa de iniciacao cientifica.
As especializacoes
Ao final do quarto semestre do curso, o aluno de Engenharia de Computacao devera optar por uma area de especializacao, escolhendo uma das habilitacoes: Sistemas de Computacao ou Sistemas e Processos Industriais.
A habilitacao Sistemas de Computacao e voltada para a area de software, com quase todas as disciplinas ministradas pelo Instituto de Computacao. Prepara o profissional para atuar no projeto e desenvolvimento de sistemas integrados de informacao, de computacao de grande porte, de rede de computadores, de software basico e aplicacoes, enfim, em atividades especificas da industria de informatica e aplicacoes.
A habilitacao Sistemas e Processos Industriais da enfase maior a integracao entre software e hardware, com a maioria das disciplinas ministrada na Faculdade de Engenharia Eletrica e de Computacao. O profissional especializado em Sistemas e Processos Industriais pode trabalhar com a construcao e a aplicacao de sistemas computacionais em areas diversas como telecomunicacoes, automacao, engenharia biomedica, sistemas de energia eletrica e outras.
